---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
{{- if .Values.hive.createGlobalPullSecret }}
  name: eso-global-pull-secret
  namespace: hive
{{- else }}
  name: eso-{{ .Values.hive.clusterName }}-pull-secret
  namespace: clusters-{{ .Values.hive.clusterName }}
{{- end }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
{{- if .Values.hive.createGlobalPullSecret }}
    name: global-pull-secret
{{- else }}
    name: {{ .Values.hive.clusterName }}-pull-secret
{{- end }}
    template:
      mergePolicy: Merge
      type: kubernetes.io/dockerconfigjson
  dataFrom:
  - extract:
  {{- if .Values.hive.createGlobalPullSecret }}
      key: {{ .Values.globalPullSecret.key }}
  {{- else }}
      key: {{ .Values.pullSecret.key }}
  {{- end }}