---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-{{ .Values.hive.clusterName }}install-config
  namespace: {{ or .Values.hive.clusterName "hive" }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
{{- if .Values.hive.createGlobalPullSecret }}
  - secretKey: globalPullSecret
    remoteRef:
      key: secret/hub/globalPullSecret
      property: .dockerconfigjson
{{- else }}
  - secretKey: pullSecret
    remoteRef:
      key: secret/hub/pullSecret
      property: .dockerconfigjson
{{- end }}
  target:
    name: {{ .Values.hive.clusterName }}-install-config
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        install-config.yaml: |
          apiVersion: v1
          baseDomain: aws.validatedpatterns.io
          compute:
          - name: worker
            platform:
              aws:
                type: m6a.xlarge
            replicas: 3
          controlPlane:
            name: master
            platform:
              aws:
                type: m6a.xlarge
            replicas: 3
          metadata:
            name: mydemo
          networking:
            clusterNetwork:
            - cidr: 10.128.0.0/14
              hostPrefix: 23
            machineNetwork:
            - cidr: 10.0.0.0/16
            serviceNetwork:
            - 172.30.0.0/16
          platform:
            aws:
              region: us-west-2
{{- if .Values.hive.createGlobalPullSecret }}
          pullSecret: {{ .globalPullSecret }}
{{- else }}
          pullSecret: {{ .pullSecret }}
{{- end }}
          sshKey: ""
