{{- if not .Values.hive.createGlobalPullSecret }}
{{- $ns := print "clusters-" .Values.hive.clusterName }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ default "eso-global" .Values.hive.clusterName }}-pull-secret
  namespace: {{ default "hive" $ns }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ default "global" .Values.hive.clusterName }}-pull-secret
    template:
      mergePolicy: Merge
      type: kubernetes.io/dockerconfigjson
  data:
   secretKey: pullSecret 
  {{- if .Values.hive.createGlobalPullSecret }}
      key: {{ .Values.globalPullSecret.key }}
  {{- else }}
      key: {{ .Values.pullSecret.key }}
  {{- end }}
      property: content
  {{- end }}
