{{- if not .Values.hive.createGlobalPullSecret }}
{{- $ns := print "clusters-" .Values.hive.clusterName }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-{{ .Values.hive.clusterName }}-aws-creds
  namespace: {{ default "hive" $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.hive.clusterName }}-{{ .Values.hive.cloud }}-creds
    template:
      mergePolicy: Merge
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.awsCredentials.key }}
{{- end }}
