apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
{{- if .Values.hive.createGlobalPullSecret }}
  globalPullSecretRef:
    name: global-pull-secret
{{- end }}
  logLevel: debug
  targetNamespace: hive
